<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>MoreFertilizerSlots</AssemblyName>
    <RootNamespace>MoreFertilizerSlots</RootNamespace>
    <Version>0.2.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" IncludeAssets="compile" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Inspector/**/*.cs" />
  </ItemGroup>
</Project>